### ISSUE TITLE
Create a sample / boilerplate project

### ISSUE THREAD

**Issue by alanta** [alanta/Kontent.Statiq#1]
Create the sample project described in the readme so people can fork it and get going quickly.
Should probably be in a separate repo.

Probably the [Kontent demo app](https://github.com/Kentico/kontent-sample-app-net) can serve as a nice base for this.

**Comment by petrsvihlik** [comment]
You can assign this one to me.

**Comment by petrsvihlik** [comment]
I think we can consider this one done
-->https://jamstackthemes.dev/#ssg=statiq&cms=kontent

**Comment by alanta** [comment]
Indeed, thanks a bunch!
