### ISSUE TITLE
Add X-KC-SOURCE header

### ISSUE THREAD

**Issue by petrsvihlik** [alanta/Kontent.Statiq#12]
Implement a tracking header according to this: https://github.com/Kentico/Home/wiki/Guidelines-for-Kontent-related-tools#analytics

Example:
| Key | Value |
|---|---|
| `X-KC-SOURCE` | `Kontent.Statiq;1.0.0-beta0004` |

**Comment by alanta** [comment]
@petrsvihlik I'd love to do this but in the current setup the main module accepts an IDeliveryClient, which doesn't allow me to inject a header.

**Comment by petrsvihlik** [comment]
let me take a look at what can be done. we definitely don't want to cut off this option in the .NET Delivery SDK

**Comment by petrsvihlik** [comment]
would this fit the needs? https://github.com/Kentico/kontent-delivery-sdk-net/pull/237

**Comment by Simply007** [comment]
I would say this one is still not closed right? It was probably closed unintentionally because of [GitHub keywords](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by alanta** [comment]
@Simply007 you're right... I need a fresh release of the delivery sdk to finish this.

**Comment by petrsvihlik** [comment]
https://www.nuget.org/packages/Kentico.Kontent.Delivery/14.0.0 here you go :)
