### ISSUE TITLE
Review Notes

### ISSUE THREAD

**Issue by petrsvihlik** [alanta/Kontent.Statiq#16]
As promised, I went through the code, and here are my findings:

**Kontent.Statiq**
- https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/Kontent.cs#L46
  - why not just `return await Task.WhenAll(documentTasks);`

- https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/SortOrder.cs
  - this class seems to be completely unnecessary

- https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/Kontent.cs#L36
  - There is no need to wrap the client in `Lazy<>`. Once an instance is injected, it's just there and there is no overhead accessing it.

**Kentico.Kontent.Delivery**
- It seems to me that `Kentico.Kontent.Delivery.Urls.QueryParameters` should be part of the `.Abstractions` library
  - It's a common logic that creates an unnecessary dependence on the Delivery SDK and even worse, on its dependencies (such as AngleSharp). Would you agree?

**Comment by alanta** [comment]
> https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/Kontent.cs#L46
> why not just return await Task.WhenAll(documentTasks);

Good catch

> https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/SortOrder.cs
> this class seems to be completely unnecessary

Agreed

> https://github.com/alanta/Kontent.Statiq/blob/main/Kontent.Statiq/Kontent.cs#L36
> There is no need to wrap the client in Lazy<>. Once an instance is injected, it's just there and there is no overhead accessing it.

Looks like a left-over from the earlier versions where the client was instantiated by the plugin. Removed it.

**Comment by alanta** [comment]
> It seems to me that Kentico.Kontent.Delivery.Urls.QueryParameters should be part of the .Abstractions library
It's a common logic that creates an unnecessary dependence on the Delivery SDK and even worse, on its dependencies (such as AngleSharp). Would you agree?

Yes, that makes sense.

**Comment by petrsvihlik** [comment]
URL generation was made public and together with the filters is part of the Kentico.Kontent.Urls package now.


https://github.com/Kentico/kontent-delivery-sdk-net/releases/tag/15.0.0-alpha4

**Comment by petrsvihlik** [comment]
not 100% sure if it's already in alpha4 but it'll certainly be in alpha5...sometime today :)

**Comment by alanta** [comment]
I'll check it out asap
