### ISSUE TITLE
KontentDownloadImages support for `Config`

### ISSUE THREAD

**Issue by petrsvihlik** [alanta/Kontent.Statiq#19]
**Is your feature request related to a problem?**
I'd like to customize paths of downloaded images based on contextual data.

**Describe the solution you'd like**
Similar to other modules that come OOTB with Statiq, I think the `KontentImageProcessor` should accept `Config<string> localPath` in the constructor.

**Describe alternatives you've considered**
`public KontentImageProcessor WithLocalPath(string path)`
-> this allows some level of customization, however, it doesn't allow me to load things from the `IDocument` and `IExecutionContext`.

**Comment by alanta** [comment]
Seems like a good enhancement, I'm picking this up for the next release
