### ISSUE TITLE
Align with Kontent Delivery SDK vNext

### ISSUE THREAD

**Issue by alanta** [alanta/Kontent.Statiq#3]
See [the milestone](https://github.com/Kentico/kontent-delivery-sdk-net/milestone/16) for the Kontent .NET SDK and the [.NET Community Backlog](https://github.com/orgs/Kentico/projects/2).

Highest impact changes are in this [PR 218](https://github.com/Kentico/kontent-delivery-sdk-net/pull/218)

Impact:
* Namespace changes, lots of namespace changes
* No more untyped responses ([more info](https://github.com/Kentico/kontent-delivery-sdk-net/wiki/Strong-Types-Explained-%E2%80%93-Runtime-Typing))
* Simpler tests (no more raw responses, everything is an interface)
* ImageUrlBuilder is moved to Kentico.Kontent.ImageTransformation nuget package

**Comment by petrsvihlik** [comment]
We released the first release candidate: https://github.com/Kentico/kontent-delivery-sdk-net/releases/edit/14.0.0-rc1

The API should not differ very much in the final version.
