### ISSUE TITLE
.NET 6 support

### ISSUE THREAD

**Issue by alanta** [alanta/Kontent.Statiq#34]
The Kontent Delivery SDK will add .NET 6 support so it's time to add support for .NET 6 as requested by @Simply007.
For now multi-targeting .NET Core 3.1 and .NET 6. Statiq is at .NET Core 3.1 so it makes sense to stick to that as the minumum requirement.

**Comment by daveaglick** [comment]
> Statiq is at .NET Core 3.1 so it makes sense to stick to that as the minimum requirement

Yep - just so it's recorded somewhere, I anticipate Statiq staying on .NET Core 3.1 for the foreseeable future. If I had to take a _wild_ guess as to when I might update to .NET 6 it would probably be late Q1/early Q2 of next year.
